# tasks file for install-elastic-repo
---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - elastic-repo

- name: install elastic yum repo key
  rpm_key:
    key: "{{ elastic_repo_gpg_key }}"
    state: "{{ elastic_repo_state }}"
  when:
    - ansible_os_family == 'RedHat'

- name: install elastic yum repository (elastic license)
  yum_repository:
    name: elastic
    description: "Elastic package repository"
    baseurl: "{{ elastic_repo_url | default(elastic_repo_url_els) }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ elastic_repo_gpg_key }}"
  when:
    - ansible_os_family == 'RedHat'
    - not (elastic_repo_oss | bool)

- name: install elastic yum repository (oss license)
  yum_repository:
    name: elastic
    description: "Elastic package repository"
    baseurl: "{{ elastic_repo_url | default(elastic_repo_url_oss) }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ elastic_repo_gpg_key }}"
  when:
    - ansible_os_family == 'RedHat'
    - elastic_repo_oss | bool
